version: '3'

services:
  ocr:
    ports:
      - 8080:8080
    command: >
      sh -c "echo Running OCR &&
          python -m uvicorn main:app --host 0.0.0.0 --port 8080 --reload > /var/log/ocr/fastapi.log 2>&1"
  ui:
    ports:
      - 8501:8501
    command: >
      sh -c "echo Running UI &&
        streamlit run app.py > /var/log/ui/streamlit.log 2>&1"